name: svf-build

# Triggers the workflow on push or pull request events
on: [push, pull_request]

# Customize the env variable
env:
  SVF_CTIR: 1
  SVF_Z3: 1
  SVF_DIR: $GITHUB_WORKSPACE
  LLVM_DIR: /usr/lib/llvm-14

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted]
        include:
          - os: [self-hosted]
            sanitizer: address
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      # setup the environment

      # build-svf
      - name: build-svf
        run: |
          cd $GITHUB_WORKSPACE
          echo $(pwd)
          if [ "${{matrix.sanitizer}}" != "" ]; then export SVF_SANITIZER="${{matrix.sanitizer}}"; fi
          if [ "$RUNNER_OS" == "Linux" ] && [ "${{matrix.sanitizer}}" == "" ]; then export SVF_COVERAGE=1; fi
          git clone "https://github.com/SVF-tools/Test-Suite.git";
          source ${{github.workspace}}/build.sh

      - name: ctest wpa
        working-directory: ${{github.workspace}}/Release-build
        run:
          ctest -R wpa_tests -V

      - name: ctest dvf and mta
        working-directory: ${{github.workspace}}/Release-build
        run:
          ctest -R dvf_tests -V

      - name: ctest andersen differential analysis
        working-directory: ${{github.workspace}}/Release-build
        run:
          ctest -R diff_tests-ander -V

      - name: ctest flow-sensitive differential analysis
        working-directory: ${{github.workspace}}/Release-build
        run:
          ctest -R diff_tests-fs -V

      - name: ctest Andersen file-write-read
        working-directory: ${{github.workspace}}/Release-build
        run:
          ctest -R diff_tests-wr-ander -V

      - name: ctest mem_leak
        working-directory: ${{github.workspace}}/Release-build
        run:
          ctest -R mem_leak -V

      - name: ctest double_free
        working-directory: ${{github.workspace}}/Release-build
        run:
          ctest -R double_free -V

      - name: ctest cfl_tests
        working-directory: ${{github.workspace}}/Release-build
        run:
          ctest -R cfl_tests -V

      - name: ctest performance tests on big cruxbc with file system diff tests
        working-directory: ${{github.workspace}}/Release-build
        if: runner.os == 'Linux' && matrix.sanitizer != 'address'
        run:
          ctest -R diff-perf-cruxbc-big -V

      - name: ctest performance tests on small cruxbc with file system diff tests
        working-directory: ${{github.workspace}}/Release-build
        if: runner.os == 'Linux'
        run:
          ctest -R diff-perf-cruxbc-small -V

      - name: create-coverage-report-and-remove-system-files
        working-directory: ${{github.workspace}}/Release-build
        if: runner.os == 'Linux' && matrix.sanitizer == ''
        run: |
          lcov --capture --directory ./ --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --remove coverage.info '${{github.workspace}}/z3.obj/*' --output-file coverage.info
          lcov --remove coverage.info '${{github.workspace}}/llvm-*.obj/*' --output-file coverage.info
          lcov --remove coverage.info '${{github.workspace}}/svf/include/FastCluster/*' --output-file coverage.info
          lcov --remove coverage.info '${{github.workspace}}/svf/lib/FastCluster/*' --output-file coverage.info
          lcov --remove coverage.info '${{github.workspace}}/svf/include/AbstractExecution/*' --output-file coverage.info
          lcov --remove coverage.info '${{github.workspace}}/svf/lib/AbstractExecution/*' --output-file coverage.info

      - name: upload-coverage
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v2
        with:
          files: coverage.info
          verbose: true
